providers = ["node"]

[variables]
# Reduce install-time downloads and disk usage
PRISMA_SKIP_POSTINSTALL_GENERATE = "1"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
NPM_CONFIG_AUDIT = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_PROGRESS = "false"
NEXT_TELEMETRY_DISABLED = "1"
# Allow esbuild to install platform-specific binaries
NPM_CONFIG_OPTIONAL = "true"

[phases.install]
cmds = [
  # Reduce disk usage: disable progress logs and clean cache (allow optional deps for esbuild)
  "npm ci --omit=dev --no-audit --no-fund --no-progress --legacy-peer-deps",
  "npm cache clean --force"
]

[phases.build]
cmds = [
  "npx prisma generate",
  # Reduce artifacts generated during build
  "NEXT_TELEMETRY_DISABLED=1 NEXT_DISABLE_SOURCEMAPS=1 npm run build"
]

[phases.setup]
cmds = []

[start]
cmd = "bash start.sh"
